language: php

os:
  - linux

env:
  global:
    # fix "Xdebug 3 is installed by default, breaking builds"
    # see https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748
    - XDEBUG_MODE=coverage

services:
  - mysql
  - postgresql
  
jobs:
  fast_finish: true
  include:
    # 1) sqlite, previous MW LTS stable, current SMW stable
    - env: DB=sqlite; MW=REL1_31; SMW=3.2.2
      php: 7.1
    # 2) postgres, current MW non-LTS stable, current SMW stable
    - env: DB=postgres; MW=REL1_34; SMW=3.2.2
      php: 7.2
    # 3) mysql, current MW LTS stable, current SMW stable, COVERAGE
    # temp run against cherry-pick SMW until SMW 3.2.3 is available
    # temp stay with MW 1.34 until all SMW tests are passing for 1.35
    - env: DB=mysql; MW=REL1_34; SMW='dev-master#229e166 as 3.2.2'; TYPE=coverage
      php: 7.3

before_install:
  # MW is not yet compatible with Composer 2.x, see https://phabricator.wikimedia.org/T266417
  - composer self-update --1
  - wget https://raw.githubusercontent.com/SemanticMediaWiki/CIScripts/main/travis/install-mediawiki.sh
  - wget https://raw.githubusercontent.com/SemanticMediaWiki/CIScripts/main/travis/install-phpunit.sh
  - wget https://raw.githubusercontent.com/SemanticMediaWiki/CIScripts/main/travis/install-semantic-mediawiki.sh
  - wget https://raw.githubusercontent.com/SemanticMediaWiki/CIScripts/main/travis/upload-scrutinizer-coverage-report.sh

install:
  - bash ./install-mediawiki.sh
  - bash ./install-phpunit.sh
  - bash ./install-semantic-mediawiki.sh
  - bash ./tests/travis/install-semantic-extra-special-properties.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./upload-scrutinizer-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
