name: CI

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          # - mediawiki_version: 1.35
          #   semantic_mediawiki_version: 4.1.1
          #   approved_revs_version: 1.8.1
          #   database_type: mysql
          #   coverage: true
          #   experimental: false
          # - mediawiki_version: 1.35
          #   semantic_mediawiki_version: 4.1.1
          #   approved_revs_version: 1.8.1
          #   database_type: sqlite
          #   coverage: false
          #   experimental: false
          # - mediawiki_version: 1.38
          #   semantic_mediawiki_version: dev-master
          #   approved_revs_version: master
          #   database_type: sqlite
          #   coverage: false
          #   experimental: true
          
          - mediawiki_version: '1.35'
            smw_version: '4.1.1'
            approved_revs_version: 1.8.1
            php_version: 7.4
            database_type: mysql
            database_image: "mysql:5.7"
            coverage: true
            experimental: false
          - mediawiki_version: '1.35'
            smw_version: '4.1.1'
            approved_revs_version: 1.8.1
            php_version: 7.4
            database_type: sqlite
            database_image: "mysql:5.7"
            coverage: true
            experimental: false
          - mediawiki_version: '1.35'
            smw_version: dev-master
            approved_revs_version: master
            php_version: 7.4
            database_type: mysql
            database_image: "mysql:5.7"
            coverage: false
            experimental: false
          - mediawiki_version: '1.39'
            smw_version: dev-master
            approved_revs_version: master
            php_version: 8.1
            database_type: mysql
            database_image: "mysql:5.7"
            coverage: false
            experimental: true
          - mediawiki_version: '1.39'
            smw_version: dev-master
            approved_revs_version: master
            php_version: 8.1
            database_type: mysql
            database_image: "mysql:8"
            coverage: false
            experimental: true
          - mediawiki_version: '1.40'
            smw_version: dev-master
            approved_revs_version: master
            php_version: 8.1
            database_type: mysql
            database_image: "mysql:8"
            coverage: false
            experimental: true
          - mediawiki_version: '1.40'
            smw_version: dev-master
            approved_revs_version: master
            php_version: 8.1
            database_type: mysql
            database_image: "mariadb:latest"
            coverage: false
            experimental: true
          - mediawiki_version: '1.40'
            smw_version: dev-master
            approved_revs_version: master
            php_version: 8.1
            database_type: postgres
            database_image: "postgres:14"
            coverage: false
            experimental: true

    env:
      MW_VERSION: ${{ matrix.mediawiki_version }}
      SMW_VERSION: ${{ matrix.smw_version }}
      AR_VERSION: ${{ matrix.approved_revs_version }}
      PHP_VERSION: ${{ matrix.php_version }}
      DB_TYPE: ${{ matrix.database_type }}
      DB_IMAGE: ${{ matrix.database_image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: make ci
        if: matrix.coverage == false

      - name: Run tests with coverage
        run: make ci-coverage
        if: matrix.coverage == true

      - name: Clean up after CI
        if: always()
        run: make destroy

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/php/coverage.xml
        if: matrix.coverage == true
