---
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - mediawiki_version: 1.35
            database_type: mysql
            semantic_mediawiki_version: 4.0.0
            coverage: true
            experimental: false
          - mediawiki_version: 1.35
            database_type: sqlite
            semantic_mediawiki_version: 4.0.0
            coverage: false
            experimental: false
          - mediawiki_version: 1.36
            database_type: sqlite
            semantic_mediawiki_version: dev-master
            coverage: false
            experimental: true
          - mediawiki_version: 1.37
            database_type: sqlite
            semantic_mediawiki_version: dev-master
            coverage: false
            experimental: true
          - mediawiki_version: 1.37
            database_type: mysql
            semantic_mediawiki_version: dev-master
            coverage: false
            experimental: true

    services:
      some-mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: database
        options: --name mysql --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10

    container:
      image: gesinn/docker-mediawiki-${{ matrix.database_type }}:${{ matrix.mediawiki_version }}
      options: --link some-mysql:mysql

    env:
      EXT_NAME: SemanticExtraSpecialProperties 
      MW_INST_PATH: /var/www/html
      MW_DB_PATH: /var/www/data
      MW_EXT_PATH: /var/www/html/extensions

    steps:
      - name: Get MySQL from dump
        working-directory: ${{ env.MW_INST_PATH }}
        run: bash restore-database.sh
        if: matrix.database_type == 'mysql'
        
      - name: Install SemanticMediaWiki
        run: |
          COMPOSER=composer.local.json composer require --update-with-dependencies --working-dir ${{ env.MW_INST_PATH }} mediawiki/semantic-media-wiki ${{ matrix.semantic_mediawiki_version }}
          composer update --working-dir ${{ env.MW_INST_PATH }}
          echo "enableSemantics( 'localhost' );" >> ${{ env.MW_INST_PATH }}/LocalSettings.php

      - name: Enable SemanticMediaWiki
        run: |
          echo "wfLoadExtension( 'SemanticMediaWiki' );" >> ${{ env.MW_INST_PATH }}/LocalSettings.php
        if: matrix.semantic_mediawiki_version == 'dev-master'

      - name: Run update
        run: |          
          php ${{ env.MW_INST_PATH }}/maintenance/update.php --skip-external-dependencies --quick

      - name: Checkout SemanticExtraSpecialProperties
        uses: actions/checkout@v2
        with:
          path: ${{ env.EXT_NAME }}

      # Setting actions/checkout@v2 path to env.MW_EXT_PATH fails with "Repository path '/var/www/html/extensions' is not under ..."
      # See also open PR https://github.com/actions/checkout/pull/388
      - name: Move SemanticExtraSpecialProperties
        run: |
          mkdir -p ${{ env.MW_EXT_PATH }}
          mv ${{ env.EXT_NAME }} ${{ env.MW_EXT_PATH }}

      - name: Install SemanticExtraSpecialProperties
        run: |
          COMPOSER=composer.local.json composer require --no-update --working-dir ${{ env.MW_INST_PATH }} mediawiki/semantic-extra-special-properties @dev
          COMPOSER=composer.local.json composer config repositories.semantic-extra-special-properties '{"type": "path", "url": "extensions/SemanticExtraSpecialProperties"}' --working-dir ${{ env.MW_INST_PATH }}
          composer update --working-dir ${{ env.MW_INST_PATH }}
          echo "wfLoadExtension( '${{ env.EXT_NAME }}' );" >> ${{ env.MW_INST_PATH }}/LocalSettings.php
          tail -n5 ${{ env.MW_INST_PATH }}/LocalSettings.php
          php ${{ env.MW_INST_PATH }}/maintenance/update.php --quick

      - name: Run Tests
        run: >
          php ${{ env.MW_INST_PATH }}/tests/phpunit/phpunit.php
          --configuration ${{ env.MW_EXT_PATH }}/${{ env.EXT_NAME }}
          --testdox
        if: matrix.coverage == false

      - name: Run Tests With Coverage
        run: >
          php ${{ env.MW_INST_PATH }}/tests/phpunit/phpunit.php
          --configuration ${{ env.MW_EXT_PATH }}/${{ env.EXT_NAME }}
          --testdox
          --coverage-clover ${{ env.MW_INST_PATH }}/docs/coverage.xml
        if: matrix.coverage == true

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ env.MW_INST_PATH }}/docs/coverage.xml
        if: matrix.coverage == true
